### ISSUE TITLE
Segítség a telepítéshez

### ISSUE THREAD

**Issue by kocsrobert** [nytud/emtsv#21]
Szervusztok!

Szeretnék segítséget kérni a telepítéshez. Windows-os gépen futtatnék elemzést, de nem működik. Letöltöttem mindent ami a futtatáshoz szükséges, de nem megy :-(

**Comment by dlazesz** [comment]
Docker-ből megy csak Windowson:

https://github.com/ELTE-DH/emtsv-wiki/blob/main/Magyar/emtsv_docker_install_imgs.md

Ha ezzel a leírással sem megy, akkor abba a repóba kérünk issue-t lérehozni, hogy javíthassuk/egyértelműsítsük a leírást.

Köszi!
