### ISSUE TITLE
Elemzés futtatása parancssorból

### ISSUE THREAD

**Issue by kocsrobert** [nytud/emtsv#22]
Köszönöm a leírást, az elemzés sikeresen lefutott. Segítséget szeretnék kérni a parancssorból való elemzés futtatásához. Korábban már írtam issue-t a másik téma alá, de sajnos nem kaptam választ. Kérhetek egy kapcsolattartó e-mail címet?

**Comment by dlazesz** [comment]
A kérdés meg lett válaszolva itt: https://github.com/ELTE-DH/emtsv-wiki/issues/1#issuecomment-831929026

Van még valami ide vonatkozó, vagy zárhatom az issue-t?
