### ISSUE TITLE
Python package-ek

### ISSUE THREAD

**Issue by BIGWarriorSoftware** [nytud/emtsv#26]
Üdv!
Szerettem volna Docker használatát megkerülve telepíteni a nyílt forráskodú project-et a gépemre Python-nal, de mindig valami függősségekbe ütköztem vele.
Az egyik ilyen függőség volt az xtsv telepítése, hiába próbáltam `pip3 install xtsv` paranccsal megoldani, nem sikerült az echo hívásos paranccsal lefuttatni, mert nem találta az xtsv module-t. Majd PyCharm-mal próbálkoztam, ott végül sikerült telepíteni a module-t, viszont újabb module hiányokkal küszködök, amit szintén nem tudok telepíteni a pip3 paranccsal, ez a `quntoken`.
A kérdés tehát: Hogyan tudom telepíteni ezeket a module-okat?
A rendszer: Windows10
Python verzió: 3.9

**Comment by dlazesz** [comment]
Windows-on Docker nélkül nem fog működni pl. a [quntoken](https://github.com/nytud/quntoken/blob/master/setup.py#L19) és az [emMorphPy](https://github.com/nytud/emmorphpy/issues/1), tehát hiába minden próbálkozás. [Windowson a Dockeres telepítésnek](https://github.com/ELTE-DH/emtsv-wiki/blob/main/Magyar/emtsv_docker_install_imgs.md) nincs alternatívája.

**Comment by BIGWarriorSoftware** [comment]
Köszönöm szépen a választ! Zárom is a témát.
