### ISSUE TITLE
Ellentmondás a dokumentáció és a docker image között (nem működik az EMTSV_NUM_PROCESSES)

### ISSUE THREAD

**Issue by gpetho** [nytud/emtsv#28]
Ezt a commitot a github-repóból: https://github.com/nytud/emtsv/commit/3eafe73 nem push-oltátok a docker registrybe (gondolom, elfelejtődött). Így továbbra is csak 2 folyamattal indul el a konténer, ha az ember (adott esetben pechemre én) a dokumentációnak megfelelően azt próbálja futtatni, hogy

```
docker run --rm -p5000:5000 -it -e "EMTSV_NUM_PROCESSES=4" mtaril/emtsv
```

Jelenleg ez csak úgy működik, ha az ember maga építi meg az `emtsv:stable` image-et a repót használva, és azt futtatja az `mtaril/emtsv` helyett.

Meg egyébként a dokumentációban ez a rész furcsán van formázva. Szerintem nem így akartátok, hogy a kódblokkban legyenek az instrukciók:

    ```bash
    docker run --rm -p5000:5000 -it mtaril/emtsv  # REST API listening on http://0.0.0.0:5000
    ```
    The container starts two emtsv processes by default. Should the throughput
    be insufficient (or conversely, the memory requirements too great even
    with two processes), this number can be configured via the
    `EMTSV_NUM_PROCESSES` variable:
    ```
    docker run --rm -p5000:5000 -it -e "EMTSV_NUM_PROCESSES=4" mtaril/emtsv
    ```

**Comment by DavidNemeskey** [comment]
Köszi az észrevételt, a felét (README.md) javítottam, a Docker Hubot inkább olyan csinálja, akinek van hozzáférése @dlazesz

**Comment by dlazesz** [comment]
Csak a rend kedvéért, a javítás itt: 54dcf6bf9d5799d2b77154ae5ad42a819179916f

A release team @mittelholcz egyszemélyben, de ő szerintem nincs feliratkozva erre a szálra. :)

**Comment by mittelholcz** [comment]
Van új [release](https://github.com/nytud/emtsv/releases/tag/v4.0.7) (4.0.7), és új [docker](https://hub.docker.com/r/mtaril/emtsv).
