### ISSUE TITLE
Furcsa, alattomos hiba: invalid character &#65279 runtime error

### ISSUE THREAD

**Issue by gpetho** [nytud/emtsv#30]
Sebességmérés közben tapasztaltam egy olyan furcsa, nehezen reprodukálható és behatárolható hibát, hogy a tok/morph/pos elemző futásidejű hibával leáll (tehát nem csak figyelmeztet, mint normális esetben), miután "rossz" karaktert olvasott be. A hiba véletlenszerűen / nem determinisztikusan lép fel, de a hibaüzenet és a viszonylag szisztematikus jelleg alapján nem valószínű, hogy a futtató rendszerből ered, hanem programhibának tűnik.

Azért ciklussal mutatom be, hogy mi történik, mert egyrészt így sokkal jobban látszik, másrészt egyszeri futtatás esetén hol fellép, hol nem.

### Lépések:
1. `docker run --rm -p5005:5000 -it mtaril/emtsv` (de a cli felülettel ugyanígy jelentkezik a hiba)
2. `for i in {1..10}; do curl localhost:5005/tok/morph/pos -F "file=@rejtorossz.txt" > outrossz.txt ; done`

### Inputfájl:
https://github.com/gpetho/rejto_rossz/blob/main/rejtorossz.txt

### A hiba leírása:
Az iterációk egy része áll le a leírt módon. A `curl` outputján annyiban látszik a hiba, hogy nem megy át a teljes 279 MB-os fájl, csak 254M-ig (első, ötödik iteráció):

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  254M    0  250M  100 4548k   342k   6229  0:12:27  0:12:27 --:--:--  376k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  279M    0  275M  100 4548k   366k   6057  0:12:48  0:12:48 --:--:--  375k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  279M    0  275M  100 4548k   367k   6071  0:12:47  0:12:47 --:--:--  379k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  279M    0  275M  100 4548k   366k   6066  0:12:47  0:12:47 --:--:--  379k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  254M    0  250M  100 4548k   368k   6689  0:11:36  0:11:36 --:--:--  376k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  279M    0  275M  100 4548k   368k   6092  0:12:44  0:12:44 --:--:--  378k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
...
```

Amikor a hibás karakterhez ér az elemző, az alkalmazásszerver a következőt írja ki:

```
...
invalid character (28089,1): ﻿
invalid character (27293,1): ﻿
invalid character (27679,1): ﻿
invalid character (28089,1): ﻿
invalid character (28666,1): ﻿

quex/quex/code_base/buffer/lexatoms/LexatomLoader_Converter.i:414:	terminate called after throwing an instance of 'std::runtime_error'
  what():  Converter produced BOM upon not-first call to 'convert'
Better make sure that converter NEVER produces BOM.
(May be, by specifiying the endianness of 'FromCoding' or 'ToCoding')

Aborted (core dumped)
```

Ezután a `curl` még jó sokáig (érzésre egy-két percig) küldi a szervernek a fájlt, tehát az outputja első oszlopában ketyegnek tovább a számok, de a szerver azokra már nem reagál. Később jön a szerver termináljában a következő output:

```
Mon Sep 20 11:10:59 2021 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /tok/morph/pos (ip 172.17.0.1) !!!
Mon Sep 20 11:10:59 2021 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /tok/morph/pos (ip 172.17.0.1) !!!
Mon Sep 20 11:10:59 2021 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /tok/morph/pos (ip 172.17.0.1) !!!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/quntoken/quntoken.py", line 31, in stdin_writer
    stdin.writelines(inp)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/quntoken/quntoken.py", line 31, in stdin_writer
    stdin.writelines(inp)
BrokenPipeError: [Errno 32] Broken pipe
```

A `curl` maga nem ad hibaüzenetet és nem áll le, hanem megy tovább a következő iterációval ezt követően.

A következő iterációnál indul egy újabb emtsv-folyamat, tehát az alkalmazásszerver is megy tovább gond nélkül, csak az emtsv-dolgozó állt le. Illetve ha több folyamat párhuzamosan fut az alkalmazásszerveren, a többi megy tovább, tehát csak az áll le, amelyik ráfutott a hibára.

A hibát kiváltó karakter a &#65279 'ZERO WIDTH NO-BREAK SPACE' (U+FEFF). A furcsa és alattomos az egészben az, hogy ebben a dokumentumban 23 darab van belőle, ez a 18., a többinél soha nem állt le nekem a futás, és ennél az egynél is véletlenszerűen / nem determinisztikusan áll le, 10 iterációból átlag kétszer-háromszor. Próbáltam volna ennek a fájlnak kisebb részletét adni inputként (próbálkoztam pár bekezdéssel a hibás karakter körül, és azzal is, hogy a fájl első kb. felét törlöm), de úgy nem jött elő a hiba.

Mindenesetre ez így együtt nagyon problémás abban a szerintem viszonylag tipikus használati esetben, amikor ciklussal dolgozunk fel párhuzamosan 10 szálon 100 ezer fájlt a korpuszunkból. A szerver outputját nézve (máshogy nem is) ugyan kiderül, hogy valamelyik fájl feldolgozása leállt hibával, de nem derül ki sehogy sem, hogy melyik.

**Comment by dlazesz** [comment]
Meg tudnád nézni, hogy csak a tokenizálóval is reprodukálható-e a hiba? Illetve emtsv nélkül csak a quntokenbe beöntve ezeket a dolgokat (pythonnal és anélkül)?

A múltkor a Python wrapperben volt a gond, ami miatt deadlock-ot kapott.

Ha Quntoken hiba, akkor azon az issue-trackeren kellene folytatni.

Köszi!

**Comment by gpetho** [comment]
> Meg tudnád nézni, hogy csak a tokenizálóval is reprodukálható-e a hiba?

Jogos, megnéztem, igen, a hiba ugyanígy jelentkezik csak a tokenizálóval az inputnak ugyanezen a pontján.



> Illetve emtsv nélkül csak a quntokenbe beöntve ezeket a dolgokat (pythonnal és anélkül)?

Nem tudom, hogy mi az a quntoken.

**Comment by dlazesz** [comment]
> Nem tudom, hogy mi az a quntoken.

https://github.com/nytud/quntoken

Python wrapperrel és CLI-ből is meg kellene nézni, hogy mi a helyzet.

Illetve ha ott nem jönne elő, akkor REST API-nélkül cat-olva az emtsv-be, de szerintem erre nem lesz szükség.

**Comment by gpetho** [comment]
A quntokenben ugyanígy véletlenszerűen előjön a hiba CLI-n.

**Comment by gpetho** [comment]
A quontoken Python-wrapperben nem tűnik reprodukálhatónak.

**Comment by dlazesz** [comment]
> A quntokenben ugyanígy véletlenszerűen előjön a hiba CLI-n.

Akkor oda nyiss egy issue-t a lényeges infókkal (az emtsv spec. dolgok nem kellenek). Hivatkozd ezt.

> A quontoken Python-wrapperben nem tűnik reprodukálhatónak.

Az vicces, mert az emtsv használja és ott megvan a hiba.

**Comment by gpetho** [comment]
> Illetve ha ott nem jönne elő, akkor REST API-nélkül cat-olva az emtsv-be, de szerintem erre nem lesz szükség.

Itt is fellépett a hiba, erre vonatkozott az "Lépések" alatt az a megjegyzés, hogy "(de a cli felülettel ugyanígy jelentkezik a hiba)"

**Comment by gpetho** [comment]
> Az vicces, mert az emtsv használja és ott megvan a hiba.

Igen, mondom, hogy alattomos.

**Comment by dlazesz** [comment]
> Itt is fellépett a hiba, erre vonatkozott az "Lépések" alatt az a megjegyzés, hogy "(de a cli felülettel ugyanígy jelentkezik a hiba)"

Valóban. Elnézést kérek.

A Quntoken CLI jó, mert ott kevés figyelemelterelő kód lesz.

**Comment by gpetho** [comment]
Ja, nem, mégis reprodukálható Pythonban is, csak épp pechem volt.

A quontoken CLI-ben tizes ciklust futtattam, abból adott esetben 6-szor jött a hiba. A Pythonban ugyanezt tettem, nem volt egyszer sem. De aztán újra futtattam egy tizes ciklust, ott a 10-ből egyszer előjött.

**Comment by gpetho** [comment]
Ezt az egészet így linkeljem be a quntokenbe egy új issue-ba, vagy másoljam át a lényeget?

**Comment by dlazesz** [comment]
> Ezt az egészet így linkeljem be a quntokenbe egy új issue-ba, vagy másoljam át a lényeget?

A Quntoken specifikus részeket másold be + ennek az issue-nak a linkjét.

Megj: Megszívtuk, ha a Quex-ben van bug, mert azt senki se fogja tudni javítani.

**Comment by gpetho** [comment]
> Megj: Megszívtuk, ha a Quex-ben van bug, mert azt senki se fogja tudni javítani.

Bekötni a quex hívása elé egy regexet, ami törli ezt a karaktert, meg esetleg másokat, amik ilyen BOM-karakterek?
Vagy berakni egy kivételkezelő ciklust, ami újra és újra odaadja a quexnek az inputsort, amíg hibát dob? (Persze nem tudom, hogy van hívva, csak ezek olyan ésszerű változatoknak tűnnek látatlanban.)

**Comment by gpetho** [comment]
Ja, egyébként a NoSketchEngine-es pull requestemet már egy bő hete módosítottam annak megfelelően, amit kértél, és a dokumentációt is, majd pillants rá, ha az időd engedi.

**Comment by dlazesz** [comment]
> > Megj: Megszívtuk, ha a Quex-ben van bug, mert azt senki se fogja tudni javítani.
> 
> Bekötni a quex hívása elé egy regexet, ami törli ezt a karaktert, meg esetleg másokat, amik ilyen BOM-karakterek?
> Vagy berakni egy kivételkezelő ciklust, ami újra és újra odaadja a quexnek az inputsort, amíg hibát dob? Miután véletlenszerűen jön a hiba, előbb-utóbb jól le fog futni. (Persze nem tudom, hogy van hívva, csak ezek olyan ésszerű változatoknak tűnnek látatlanban.)

Vagy akár updatelhetnénk a Quex-et hátha ott már nincs ez az issue és ha mégis küldhetnénk be róla bug reportot. Kb ugyanennyi idő.

**Comment by gpetho** [comment]
Így szerintem ez le is zárható.

**Comment by dlazesz** [comment]
Lezárom. A https://github.com/nytud/quntoken/issues/42 -be delegáltuk a problémát. Majd ha megoldódik frissíteni kell a quntokent, más dolog itt nincs.
