### ISSUE TITLE
Ékezetes karakterek nem működnek curl-el

### ISSUE THREAD

**Issue by BIGWarriorSoftware** [nytud/emtsv#31]
Üdv!

Mivel API-ban továbbra sincs feloldva a CORS, Docker hub-on találtam egy olyan megoldást, ami cUrl-el biztosít parancsküldést az EMTSV-hez, ami működik, viszont mintha az ékezetes karaktereket nem tudná feldolgozni ezen keresztül, és az elemzés is úgy jön vissza, hogy az ékezetes karaktereket kihagyja, és ketté szeli a szót onnantól. Van olyan modul, ami ezt tudná szolgálni, vagy csak én nem látom?

A választ előre is köszönöm!
M

**Comment by DavidNemeskey** [comment]
Nem lehet, hogy ez valami encoding probléma? Sajnos a parancs nélkül nehéz bármit is mondani. Légyszíves küldd el a következőket:
1. A pontos `curl` parancsot
2. Milyen oprendszert használsz?
3. Mi a lokálod? (Linux alatt a `locale` parancs kimenete)

Köszi!

**Comment by DavidNemeskey** [comment]
Szóval nekem ez a parancs működik (UTF-8 locale alatt):
```
curl --data-urlencode 'text=A kutya elment sétálni.' -H 'Content-Type: application/x-www-form-urlencoded' http://localhost:5000/tok/morph/pos
```

**Comment by BIGWarriorSoftware** [comment]
Szia!
Küldöm:
1. curl -F "text=Begépelem a helyes kódot" http://localhost:5000/tok/morph/pos/conv-morph/dep
2. Windows 10/11
3. Erre nem találtam sajnos parancsot a WSL alatt. :-/

Kipróbáltam azt, amit másodjára küldtél, de sajnos ugyanazt tapasztalom. De ha van a WSL alatt valami lokalizációs parancs, azzal beljebb lennék.

Üdv,
M

> Nem lehet, hogy ez valami encoding probléma? Sajnos a parancs nélkül nehéz bármit is mondani. Légyszíves küldd el a következőket:
> 
> 1. A pontos `curl` parancsot
> 2. Milyen oprendszert használsz?
> 3. Mi a lokálod? (Linux alatt a `locale` parancs kimenete)
> 
> Köszi!

**Comment by DavidNemeskey** [comment]
Szerintem a hiba az Ön készülékében van. Nekem WSL alatt egyrészt működik a fenti `curl -F`, másrészt a `locale` parancs is. De akkor próbálj meg két dolgot:
1. `curl -v -F "text=Begépelem a helyes kódot" http://localhost:5000/tok/morph/pos/conv-morph/dep`, és másold ide be a kimenetet
2. `echo "Begépelem a helyes kódot" > x; file -bi x`, és másold be ezt is kérlek.

Köszi!

**Comment by DavidNemeskey** [comment]
@BIGWarriorSoftware egyébként `locale` helyett megpróbálhatod az `env | grep LANG` parancsot is.

**Comment by BIGWarriorSoftware** [comment]
Talán ez a lokálom:
LANG=C.UTF-8                                                                                                            LANGUAGE=                                                                                                               LC_CTYPE="C.UTF-8"                                                                                                      LC_NUMERIC="C.UTF-8"                                                                                                    LC_TIME="C.UTF-8"                                                                                                       LC_COLLATE="C.UTF-8"                                                                                                    LC_MONETARY="C.UTF-8"                                                                                                   LC_MESSAGES="C.UTF-8"                                                                                                   LC_PAPER="C.UTF-8"                                                                                                      LC_NAME="C.UTF-8"                                                                                                       LC_ADDRESS="C.UTF-8"                                                                                                    LC_TELEPHONE="C.UTF-8"                                                                                                  LC_MEASUREMENT="C.UTF-8"                                                                                                LC_IDENTIFICATION="C.UTF-8"                                                                                             LC_ALL=

> @BIGWarriorSoftware egyébként `locale` helyett megpróbálhatod az `env | grep LANG` parancsot is.

**Comment by BIGWarriorSoftware** [comment]
**1.** *-es kérésre:   Trying ::1...                                                                                                                                                                             * TCP_NODELAY set                                                                                                                                                                             * Connected to localhost (::1) port 5000 (#0)                                                                                                                                                 > POST /tok/morph/pos/conv-morph/dep HTTP/1.1                                                                                                                                                 > Host: localhost:5000                                                                                                                                                                        > User-Agent: curl/7.55.1                                                                                                                                                                     > Accept: */*                                                                                                                                                                                 > Content-Length: 163                                                                                                                                                                         > Expect: 100-continue                                                                                                                                                                        > Content-Type: multipart/form-data; boundary=------------------------3e2e4c328439b1df                                                                                                        >                                                                                                                                                                                             * Done waiting for 100-continue                                                                                                                                                               < HTTP/1.1 200 OK                                                                                                                                                                             < Content-Type: text/plain; charset=utf-8                                                                                                                                                     < Content-Disposition: attachment; filename=output.txt                                                                                                                                        * no chunk, no close, no size. Assume close to signal end                                                                                                                                     <                                                                                                                                                                                             form    wsafter anas    lemma   xpostag upostag feats   id      deprel  head                                                                                                                  Beg     ""      []      Beg     [/N][Nom]       PROPN   Case=Nom|Number=Sing    1       ATT     2                                                                                             �       ""      []      �       [/N][Nom]       NOUN    Case=Nom|Number=Sing    2       SUBJ    3                                                                                             pelem   " "     []      pelem   [/V][Pst.Def.1Sg]       VERB    Definite=Def|Mood=Ind|Number=Sing|Person=1|Tense=Past|VerbForm=Fin|Voice=Act    3       ROOT    0                             a       " "     [{"lemma": "a", "tag": "[/Det|Art.Def]", "morphana": "a[/Det|Art.Def]=a", "readable": "a[/Det|Art.Def]", "twolevel": "a:a :[/Det|Art.Def]"}, {"lemma": "a", "tag": "[/Det|Pro|(Post)]", "morphana": "a[/Det|Pro|(Post)]=a", "readable": "a[/Det|Pro|(Post)]", "twolevel": "a:a :[/Det|Pro|(Post)]"}, {"lemma": "a", "tag": "[/N][Nom]", "morphana": "a[/N|Ltr]=a+[Nom]=", "readable": "a[/N|Ltr] + [Nom]", "twolevel": "a:a :[/N|Ltr] :[Nom]"}, {"lemma": "a", "tag": "[/N|Pro|(Post)][Nom]", "morphana": "a[/N|Pro|(Post)]=a+[Nom]=", "readable": "a[/N|Pro|(Post)] + [Nom]", "twolevel": "a:a :[/N|Pro|(Post)] :[Nom]"}]        a       [/Det|Art.Def]  DET     Definite=Def|PronType=Art       4       DET     6                                                     helyes  " "     [{"lemma": "helyes", "tag": "[/Adj][Nom]", "morphana": "hely[/N]=hely+es[_Adjz:s/Adj]=es+[Nom]=", "readable": "hely[/N] + es[_Adjz:s/Adj] + [Nom]", "twolevel": "h:h e:e l:l y:y :[/N] e:e s:s :[_Adjz:s/Adj] :[Nom]"}, {"lemma": "helyes", "tag": "[/N][Nom]", "morphana": "hely[/N]=hely+es[_Nz:s/N]=es+[Nom]=", "readable": "hely[/N] + es[_Nz:s/N] + [Nom]", "twolevel": "h:h e:e l:l y:y :[/N] e:e s:s :[_Nz:s/N] :[Nom]"}, {"lemma": "helyes", "tag": "[/Adj][Nom]", "morphana": "helyes[/Adj]=helyes+[Nom]=", "readable": "helyes[/Adj] + [Nom]", "twolevel": "h:h e:e l:l y:y e:e s:s :[/Adj] :[Nom]"}]   helyes  [/Adj][Nom]     ADJ     Case=Nom|Degree=Pos|Number=Sing 5       ATT     6                                                                     k       ""      [{"lemma": "k", "tag": "[/N][Nom]", "morphana": "k[/N|Ltr]=k+[Nom]=", "readable": "k[/N|Ltr] + [Nom]", "twolevel": "k:k :[/N|Ltr] :[Nom]"}]     k       [/N][Nom]       NOUN Case=Nom|Number=Sing     6       ATT     7                                                                                                                                                     �       ""      []      �       [/Adj][Nom]     ADJ     Case=Nom|Degree=Pos|Number=Sing 7       ATT     8                                                                                     dot     ""      []      d       [/N][Nom]       NOUN    Case=Nom|Number=Sing    8       OBJ     3                                                                                                                                                                                                                                                                                           * Closing connection 0 
**2.** -es kérésre:
text/plain; charset=utf-8

> Szerintem a hiba az Ön készülékében van. Nekem WSL alatt egyrészt működik a fenti `curl -F`, másrészt a `locale` parancs is. De akkor próbálj meg két dolgot:
> 
> 1. `curl -v -F "text=Begépelem a helyes kódot" http://localhost:5000/tok/morph/pos/conv-morph/dep`, és másold ide be a kimenetet
> 2. `echo "Begépelem a helyes kódot" > x; file -bi x`, és másold be ezt is kérlek.
> 
> Köszi!

**Comment by DavidNemeskey** [comment]
Szia! A gyanúm beigazolódni látszik. Elküldtem terminálból a fenti curl paranccsal a mondatodat, és egyfelől az emtsv jól elemezte, másfelől 165 byte hosszú volt, a Te 163-addal szemben. Csináltam egy másik tesztet is:
```
echo "text=Begépelem a helyes kódot" > input.utf8
iconv -f utf-8 -t iso-8859-2 input.utf8 > input.latin2
curl -v -F `cat input.utf8` <emtsv_url>
curl -v -F `cat input.latin2` <emtsv_url>
```
Itt az első curl jó eredményt ad vissza, a Content-Length 165; a második a te kimenetedet reprodukálja, és a hossz 163.

Szóval nem tudom, hogyan (mivel a locale utf8-nak tűnik a leírásod alapján), de valahogy Latin-2-es inputot küldesz. Lehet, hogy terminál program beállítása a rossz, vagy ha kódból hívod a curl-t, akkor a kódfile/editor lehet Latin-2-re állítva (vagy Windows-1252-re).

**Comment by BIGWarriorSoftware** [comment]
> Szóval nem tudom, hogyan (mivel a locale utf8-nak tűnik a leírásod alapján), de valahogy Latin-2-es inputot küldesz. Lehet, hogy terminál program beállítása a rossz, vagy ha kódból hívod a curl-t, akkor a kódfile/editor lehet Latin-2-re állítva (vagy Windows-1252-re).

Igen, egy általam kreált C# alkalmazásból próbálom az elemzést csinálni [Process](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process?view=net-5.0)/[ProcessStartInfo](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo?view=net-5.0) segítségével, ahová most már a StandardInputEncoding/StandardOutputEncoding/StandardErrorEncoding is utf8-as kódolású, viszont még mindig ugyanazt a hibát tapasztalom. Próbálom kideríteni, hol megy át latin2-es kódolás, de egyelőre 'tűt a szénakazalban'...

> Szia! A gyanúm beigazolódni látszik. Elküldtem terminálból a fenti curl paranccsal a mondatodat, és egyfelől az emtsv jól elemezte, másfelől 165 byte hosszú volt, a Te 163-addal szemben. Csináltam egy másik tesztet is:
> 
> ```
> echo "text=Begépelem a helyes kódot" > input.utf8
> iconv -f utf-8 -t iso-8859-2 input.utf8 > input.latin2
> curl -v -F `cat input.utf8` <emtsv_url>
> curl -v -F `cat input.latin2` <emtsv_url>
> ```
> 
> Itt az első curl jó eredményt ad vissza, a Content-Length 165; a második a te kimenetedet reprodukálja, és a hossz 163.
> 
> Szóval nem tudom, hogyan (mivel a locale utf8-nak tűnik a leírásod alapján), de valahogy Latin-2-es inputot küldesz. Lehet, hogy terminál program beállítása a rossz, vagy ha kódból hívod a curl-t, akkor a kódfile/editor lehet Latin-2-re állítva (vagy Windows-1252-re).

**Comment by BIGWarriorSoftware** [comment]
Meg kell erősítsem az álláspontodat, a hiba valóban a Windows PowerShell chcp-jében volt.
Ezen kell végigmennem, mire UTF-8 kódolással működött minden:
[link](https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window)

Úgyhogy nagyon köszönöm, hogy rávilágítottál a problémára, a szoftver ismét elvárt módon működik.

Ha nincs más mondanivaló, akkor holnap zárom is ezt az issue-t.
Köszönettel,
M

> Szia! A gyanúm beigazolódni látszik. Elküldtem terminálból a fenti curl paranccsal a mondatodat, és egyfelől az emtsv jól elemezte, másfelől 165 byte hosszú volt, a Te 163-addal szemben. Csináltam egy másik tesztet is:
> 
> ```
> echo "text=Begépelem a helyes kódot" > input.utf8
> iconv -f utf-8 -t iso-8859-2 input.utf8 > input.latin2
> curl -v -F `cat input.utf8` <emtsv_url>
> curl -v -F `cat input.latin2` <emtsv_url>
> ```
> 
> Itt az első curl jó eredményt ad vissza, a Content-Length 165; a második a te kimenetedet reprodukálja, és a hossz 163.
> 
> Szóval nem tudom, hogyan (mivel a locale utf8-nak tűnik a leírásod alapján), de valahogy Latin-2-es inputot küldesz. Lehet, hogy terminál program beállítása a rossz, vagy ha kódból hívod a curl-t, akkor a kódfile/editor lehet Latin-2-re állítva (vagy Windows-1252-re).
