### ISSUE TITLE
Lassú lekérdezés cURL-el

### ISSUE THREAD

**Issue by BIGWarriorSoftware** [nytud/emtsv#34]
Üdv!

Köszönöm az eddigi segítséget a cURL-el kapcsolatban. Viszont most egy másik, teljesítménybeli problémára szeretnék megoldást találni.

Adott ez a parancs:
`curl -v -F "text=Lassú a lekérdezés." http://localhost:5000/tok-dep`

Bármennyi lekérdezés 30-másfél perc lekérdezési időt eredményez. Hogy lehet ezen a teljesítményen javítani? Van-e valami cache-elési megoldása ennek?

Köszönettel

**Comment by DavidNemeskey** [comment]
Szia!

Nem csak az első 1-2 (vagy ahány szálon megy az emtsv, alapból azt hiszem 2) lekérdezés lassú? Mert akkor az feltehetően annak köszönhető, hogy akkor tölti be a modelleket...

**Comment by BIGWarriorSoftware** [comment]
Szia!
De. És ráadásul megint az én gépezetemben volt a probléma... :) Egy szálat addig tartottam fenn, amíg a lekérdezés tartott, utána azt megöltem, így amikor a szoftver újabb lekérdezést indított, újabb szálat vett fel, amit a végén ismét megölt.

Köszi a segítséget!
M.

> Szia!
> 
> Nem csak az első 1-2 (vagy ahány szálon megy az emtsv, alapból azt hiszem 2) lekérdezés lassú? Mert akkor az feltehetően annak köszönhető, hogy akkor tölti be a modelleket...
