### ISSUE TITLE
web frontend using docker

### ISSUE THREAD

**Issue by sassbalint** [nytud/emtsv#39]
Please, help, how to get the web frontend running using the docker image?

**Comment by dlazesz** [comment]
1. [Run the container](https://github.com/nytud/emtsv#as-service-through-rest-api-docker-container)
2. Navigate to: [http://127.0.0.1:5000/](http://127.0.0.1:5000/) (or whatever IP and port the service is bound to, the root path (/) is the frontend, any parameters are the module names, etc.)

Would you mind to propose a PR for the documentation?

**Comment by sassbalint** [comment]
> 1. [Run the container](https://github.com/nytud/emtsv#as-service-through-rest-api-docker-container)
> 
>     2. Navigate to: [http://127.0.0.1:5000](http://127.0.0.1:5000/) (or whatever IP and port the service is bound to, the root path (/) is the frontend, any parameters are the module names, etc.)

Thanks. :+1:
 
> Would you mind to propose a PR for the documentation?

It is my pleasure. :smiley: :smiley: :arrow_right: https://github.com/nytud/emtsv/pull/40

**Comment by dlazesz** [comment]
#40 is merged. Thank you!
