### ISSUE TITLE
`emCompound` and `emPreverb` together on the simple web frontend

### ISSUE THREAD

**Issue by sassbalint** [nytud/emtsv#41]
|module|descr @ web frontend|
|--|--|
|`preverb` |connect preverbs|
|`compound`|annotate compound boundaries|

CLI test:

|modules|works?|
|:--:|:--:|
|`compound`|:heavy_check_mark:|
|`preverb`|:heavy_check_mark:|
|`compound` and then `preverb`|:heavy_check_mark:|
|`preverb` and then `compound`|:angry:|

Choosing `compound` and `preverb` both on the web frontend gives empty output.
__The problem is maybe they are called in the wrong order.__
Check, and fix the order of these modules, please.

Thanks. :+1:

**Comment by dlazesz** [comment]
Logs please.
