### ISSUE TITLE
emConll should be the last module in the enumeration on the WebUI

### ISSUE THREAD

**Issue by dlazesz** [nytud/emtsv#42]
For example dependency parsing with emStanza can be converted to ConLL-U format only in two separate steps from the WebUI, because [the current module order](https://github.com/nytud/emtsv/blob/master/config.py#L218). E.g. emConll preceeds emStanza-dep which requires the emtsv format. -> Error.

Changing the module order would allow executing the above pipeline in one step.

**Comment by sassbalint** [comment]
#41 is somewhat similar.
